import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700"],
  style: ["normal","italic"],
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibmPlexSans.className}>
      <head>
        <link rel="icon" href="/logo.png" type="image/png" />
        <link rel="apple-touch-icon" href="/logo.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#651818" />
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
